services:
  - name: postiz-app
    type: web
    env: node
    plan: starter
    buildCommand: >
      npm install &&
      npm run prisma-generate &&
      npm run prisma-db-push &&
      npx nx run-many --target=build --all --parallel
    startCommand: >
      npx nx run-many --target=serve --projects=backend,frontend --parallel
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: "10000" # Port par défaut de Render
      - key: DATABASE_URL
        sync: false    # à définir dans le dashboard Render (valeur secrète)
      - key: REDIS_URL
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: FRONTEND_URL
        sync: false
      - key: NEXT_PUBLIC_BACKEND_URL
        sync: false
      - key: BACKEND_INTERNAL_URL
        sync: false
