services:
  - type: web             # Service web Node.js pour frontend+backend
    name: postiz-app
    runtime: node
    plan: starter        # ou free (selon le compte)
    buildCommand: >
      npm install &&
      npm run prisma-generate &&
      npm run prisma-db-push &&
      nx run-many --target=build --all --parallel
    startCommand: >
      nx run-many --target=serve --projects=backend,frontend --parallel
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: "10000"
      - key: DATABASE_URL        # Connexion à la BD (Supabase Postgres)
      - key: REDIS_URL           # Connexion à Redis
      - key: JWT_SECRET          # Secret JWT
      - key: FRONTEND_URL        # Ex. https://nom-de-votre-app.onrender.com
      - key: NEXT_PUBLIC_BACKEND_URL
      - key: BACKEND_INTERNAL_URL
      # (Ajouter ici d’autres variables si besoin, e.g. CLOUDFLARE_... pour R2, clés OAuth, etc.)
